version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: customer-api
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    restart: unless-stopped

volumes:
  pgdata:
  air_tmp: